### ISSUE TITLE
Update to chardet 3.0.4

### ISSUE THREAD

**Issue by beenje** [vially/xbmc-chardet#1]
Hi,

I want to update the script.module.requests add-on. chardet used to be bundled with requests but isn't anymore.
The current version of requests (2.18.4) requires 'chardet>=3.0.2,<3.1.0'.

I could send a pull request if you want.

**Comment by vially** [comment]
Unfortunately I haven't been involved in kodi addon development for quite some time now so I haven't kept this repository up-to-date.

I think the best course of action for getting `chardet` updated in the kodi repositories would be to follow the Kodi guidelines for [submitting addons](http://kodi.wiki/view/Submitting_Add-ons). This means submitting a pull request against the [repo-scripts](https://github.com/xbmc/repo-scripts) repository.

You can use the old [Gotham version](https://github.com/xbmc/repo-scripts/tree/gotham/script.module.chardet) of this addon as a starting point. When you're done make sure to submit your PR against the branch corresponding to the version of Kodi you want to support (e.g.: `krypton` or `leia` most probably).

So what I'm trying to say is that there's no point in sending a PR against my repo when you can send it directly against the kodi addons repository.

I hope this helps.

**Comment by beenje** [comment]
Thanks for the reply.
Only the maintainer of the addon is supposed to make a PR (which makes sense). But if you are not interested in maintaining this addon, I can take over and submit a PR against Kodi repo-scripts.

**Comment by vially** [comment]
Sure, feel free to take over. I don't think the Kodi maintainers will ask for my consent on this but if they do feel free to point them to this conversation.

**Comment by beenje** [comment]
OK. Thanks!
